### ISSUE TITLE
Listing unavailable videos

### ISSUE THREAD

**Issue by darvid7** [Gecko420/Gecko420-App#17]
Handle case where isFuture is true and hasAvailableVideo is false, seen in getMediaLessonsJson. Seems to be linked to red button error on Monash SS.

**Comment by darvid7** [comment]
Might be resolved by checking [lesson.hasAvaliableVideo](https://github.com/Gecko420/Gecko420-App/commit/eaa0913376afa562437b8dba39cf89b39ffce3d1)

**Comment by lorderikir** [comment]
This has been fixed in #18
